//! ECS-first scene stack primitives for Foundation games.
//!
//! The scene stack is data-driven: games and systems request stack mutations by
//! writing [`SceneCommand`] messages, while Foundation systems own the stack
//! resource and lifecycle messages. Bevy BSN levels are represented as a
//! scene source instead of being converted into a separate Foundation-specific
//! scene format.

use bevy::prelude::*;

/// Installs FoundationRuntimeLibrary scene stack resources and message types.
#[derive(Default)]
pub struct FoundationSceneStackPlugin;

impl Plugin for FoundationSceneStackPlugin {
    fn build(&self, app: &mut App) {
        // The stack resource owns scene lifecycle; messages are the public mutation API.
        app.init_resource::<SceneStack>()
            .add_message::<SceneCommand>()
            .add_message::<SceneAdded>()
            .add_message::<SceneRemoved>()
            .add_message::<SceneFocused>()
            .add_message::<SceneUnfocused>()
            .add_message::<SceneLoadRequested>()
            .register_type::<SceneOwner>()
            .register_type::<SceneContentLoading>()
            // Visibility sync and cleanup run after command processing so both
            // observe the freshly recomputed stack flags and removed scene IDs.
            .add_systems(
                PostUpdate,
                (
                    process_scene_commands,
                    sync_scene_entity_visibility,
                    cleanup_removed_scene_entities,
                )
                    .chain(),
            );
    }
}

/// Stable runtime identifier for a scene stack entry.
///
/// IDs are generated by the scene stack when an open command is applied. Use
/// [`SceneKey`] when game code needs a stable human-authored target.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash, Reflect)]
pub struct SceneId(pub u64);

/// Optional human-authored scene key for targeting and diagnostics.
#[derive(Clone, Debug, PartialEq, Eq, Hash, Reflect)]
pub struct SceneKey(pub String);

impl SceneKey {
    /// Creates a scene key from any string-like value.
    pub fn new(value: impl Into<String>) -> Self {
        Self(value.into())
    }
}

impl From<&str> for SceneKey {
    fn from(value: &str) -> Self {
        Self::new(value)
    }
}

impl From<String> for SceneKey {
    fn from(value: String) -> Self {
        Self::new(value)
    }
}

/// Describes where scene content comes from.
///
/// BSN scene keys are first-class sources so FoundationRuntimeLibrary can cooperate
/// with code-authored BSN scenes without defining a second scene-stack API.
#[derive(Clone, Debug, PartialEq, Eq, Reflect)]
pub enum SceneSource {
    /// A Bevy BSN scene key resolved by the active game catalog.
    BsnScene { key: String },
    /// A runtime scene identified by key, such as a menu or overlay assembled by systems.
    Runtime { key: SceneKey },
}

impl SceneSource {
    /// Creates a source for a Bevy BSN scene key.
    pub fn bsn_scene(key: impl Into<String>) -> Self {
        Self::BsnScene { key: key.into() }
    }

    /// Creates a source for a runtime/system-authored scene.
    pub fn runtime(key: impl Into<SceneKey>) -> Self {
        Self::Runtime { key: key.into() }
    }
}

/// Describes how a scene affects scenes below it in the stack.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Reflect)]
pub struct ScenePresentation {
    /// If true, scenes below this one should not be visible.
    pub covers_previous: bool,
    /// If true, scenes below this one should not receive input.
    pub blocks_previous_input: bool,
    /// If true, scenes below this one should not update/simulate.
    pub blocks_previous_update: bool,
}

impl ScenePresentation {
    /// Full-screen/modal scene: hides, blocks input, and blocks updates below.
    pub const FULLSCREEN: Self = Self {
        covers_previous: true,
        blocks_previous_input: true,
        blocks_previous_update: true,
    };

    /// Pause-style overlay: keeps lower scenes visible but blocks input and updates.
    pub const PAUSE_OVERLAY: Self = Self {
        covers_previous: false,
        blocks_previous_input: true,
        blocks_previous_update: true,
    };

    /// UI overlay: keeps lower scenes visible/updating but blocks their input.
    pub const INPUT_BLOCKING_OVERLAY: Self = Self {
        covers_previous: false,
        blocks_previous_input: true,
        blocks_previous_update: false,
    };

    /// Debug-style overlay: leaves lower scenes visible, interactive, and updating.
    pub const NON_BLOCKING_OVERLAY: Self = Self {
        covers_previous: false,
        blocks_previous_input: false,
        blocks_previous_update: false,
    };
}

impl Default for ScenePresentation {
    fn default() -> Self {
        Self::FULLSCREEN
    }
}

/// Derived runtime flags for a scene stack entry.
///
/// Foundation enforces these flags for scene-owned entities: `visible` drives
/// [`Visibility`] on scene-root entities each frame, and Foundation gameplay
/// systems skip entities whose scene is not `updating`. Game systems should
/// consult [`SceneStack::is_updating`] for their own update gating.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Reflect)]
pub struct SceneRuntimeFlags {
    /// True when this scene owns primary focus.
    pub focused: bool,
    /// True when this scene should be visible.
    pub visible: bool,
    /// True when this scene may receive input.
    pub interactive: bool,
    /// True when this scene should update/simulate.
    pub updating: bool,
}

/// A single entry in the scene stack.
#[derive(Clone, Debug, PartialEq, Eq, Reflect)]
pub struct SceneStackEntry {
    /// Generated runtime id for this stack entry.
    pub id: SceneId,
    /// Optional stable target key for game-friendly lookup.
    pub key: Option<SceneKey>,
    /// Data source for the scene.
    pub source: SceneSource,
    /// Policy describing how this scene affects lower stack entries.
    pub presentation: ScenePresentation,
    /// Derived focus/visibility/input/update flags.
    pub flags: SceneRuntimeFlags,
}

/// Authoritative scene stack resource.
#[derive(Debug, Resource, Reflect)]
#[reflect(Resource)]
pub struct SceneStack {
    entries: Vec<SceneStackEntry>,
    next_id: u64,
}

impl Default for SceneStack {
    fn default() -> Self {
        Self {
            entries: Vec::new(),
            next_id: 1,
        }
    }
}

impl SceneStack {
    /// Returns all stack entries from bottom to top.
    pub fn entries(&self) -> &[SceneStackEntry] {
        &self.entries
    }

    /// Returns the top stack entry, if any.
    pub fn current(&self) -> Option<&SceneStackEntry> {
        self.entries.last()
    }

    /// Finds a scene by generated id.
    pub fn get(&self, id: SceneId) -> Option<&SceneStackEntry> {
        self.entries.iter().find(|entry| entry.id == id)
    }

    /// Finds a scene by game-authored key.
    pub fn get_by_key(&self, key: &SceneKey) -> Option<&SceneStackEntry> {
        self.entries
            .iter()
            .find(|entry| entry.key.as_ref() == Some(key))
    }

    /// Returns the currently focused scene, if any.
    pub fn focused(&self) -> Option<&SceneStackEntry> {
        self.entries.iter().find(|entry| entry.flags.focused)
    }

    /// Returns true when no scenes are stacked.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Returns the number of stacked scenes.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Returns the next id that will be assigned by command processing.
    pub fn next_scene_id(&self) -> SceneId {
        SceneId(self.next_id)
    }

    /// Returns true when the scene with this id should update/simulate.
    ///
    /// Unknown ids report false so entities owned by removed scenes never keep
    /// running while their cleanup is pending.
    pub fn is_updating(&self, id: SceneId) -> bool {
        self.get(id).is_some_and(|entry| entry.flags.updating)
    }

    /// Returns true when the scene with this id should be visible.
    ///
    /// Unknown ids report false so entities owned by removed scenes never stay
    /// visible while their cleanup is pending.
    pub fn is_visible(&self, id: SceneId) -> bool {
        self.get(id).is_some_and(|entry| entry.flags.visible)
    }

    fn allocate_id(&mut self) -> SceneId {
        // Scene IDs are monotonic so stale IDs are never reused within one app run.
        let id = SceneId(self.next_id);
        self.next_id += 1;
        id
    }
}

/// Options used when opening a scene.
#[derive(Clone, Debug, Default, PartialEq, Eq, Reflect)]
pub struct OpenSceneOptions {
    /// Optional stable key for closing or finding the scene later.
    pub key: Option<SceneKey>,
    /// Presentation policy for the new scene.
    pub presentation: ScenePresentation,
    /// Remove all existing scenes before opening this scene.
    pub clear_stack: bool,
    /// Remove the current top scene before opening this scene.
    pub close_current: bool,
}

impl OpenSceneOptions {
    /// Sets the scene key.
    pub fn with_key(mut self, key: impl Into<SceneKey>) -> Self {
        self.key = Some(key.into());
        self
    }

    /// Sets the scene presentation policy.
    pub fn with_presentation(mut self, presentation: ScenePresentation) -> Self {
        self.presentation = presentation;
        self
    }

    /// Configures the open command to clear all existing scenes first.
    pub fn clear_stack(mut self) -> Self {
        self.clear_stack = true;
        self
    }

    /// Configures the open command to close the current top scene first.
    pub fn close_current(mut self) -> Self {
        self.close_current = true;
        self
    }
}

/// Target used by close commands.
#[derive(Clone, Debug, PartialEq, Eq, Reflect)]
pub enum SceneTarget {
    /// Close the scene with this generated id.
    Id(SceneId),
    /// Close the first scene with this game-authored key.
    Key(SceneKey),
}

impl From<SceneId> for SceneTarget {
    fn from(value: SceneId) -> Self {
        Self::Id(value)
    }
}

impl From<SceneKey> for SceneTarget {
    fn from(value: SceneKey) -> Self {
        Self::Key(value)
    }
}

/// Buffered request to mutate the scene stack.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub enum SceneCommand {
    /// Open a scene, optionally clearing or replacing existing entries first.
    Open {
        /// Scene source to open.
        source: SceneSource,
        /// Open behavior and presentation options.
        options: OpenSceneOptions,
    },
    /// Close the current top scene.
    CloseCurrent,
    /// Close a specific scene by id or key.
    Close(SceneTarget),
    /// Remove all scenes from the stack.
    Clear,
    /// Remove all scenes, then open the supplied scene.
    ClearAndOpen {
        /// Scene source to open after clearing.
        source: SceneSource,
        /// Open behavior and presentation options.
        options: OpenSceneOptions,
    },
}

impl SceneCommand {
    /// Creates an open command with default options.
    pub fn open(source: SceneSource) -> Self {
        Self::Open {
            source,
            options: OpenSceneOptions::default(),
        }
    }

    /// Creates an open command with explicit options.
    pub fn open_with_options(source: SceneSource, options: OpenSceneOptions) -> Self {
        Self::Open { source, options }
    }

    /// Creates a clear-and-open command with default open options.
    pub fn clear_and_open(source: SceneSource) -> Self {
        Self::ClearAndOpen {
            source,
            options: OpenSceneOptions::default(),
        }
    }
}

/// Message emitted after a scene is added to the stack.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub struct SceneAdded {
    /// Added scene id.
    pub scene_id: SceneId,
}

/// Message emitted after a scene is removed from the stack.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub struct SceneRemoved {
    /// Removed scene id.
    pub scene_id: SceneId,
}

/// Message emitted after a scene becomes focused.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub struct SceneFocused {
    /// Focused scene id.
    pub scene_id: SceneId,
}

/// Message emitted after a scene loses focus.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub struct SceneUnfocused {
    /// Unfocused scene id.
    pub scene_id: SceneId,
}

/// Message emitted when scene content should be loaded or assembled.
///
/// Systems that bridge to Bevy BSN loading should listen for this message,
/// load the requested [`SceneSource`], and tag spawned entities with
/// [`SceneOwner`] using the supplied scene id.
#[derive(Clone, Debug, Message, PartialEq, Eq, Reflect)]
pub struct SceneLoadRequested {
    /// Scene that should receive the loaded content.
    pub scene_id: SceneId,
    /// Source that describes what content should be loaded or assembled.
    pub source: SceneSource,
}

/// Tags entities that are owned by a scene stack entry.
///
/// Scene-owned entities should remain alive while their owning scene is in the
/// stack and be cleaned up when that scene is removed.
#[derive(Clone, Copy, Debug, Default, Component, PartialEq, Eq, Reflect)]
#[reflect(Component)]
pub struct SceneOwner {
    /// Scene that owns this entity.
    pub scene_id: SceneId,
}

/// Marks an entity whose content is not fully ready to display yet.
///
/// Attach this to a [`SceneOwner`]-tagged entity — the scene root or any
/// descendant — while its authored content is still loading or applying.
/// [`FoundationSceneStackPlugin`]'s visibility sync keeps every entity owned
/// by that scene hidden until no entity it owns still carries this marker,
/// even if the scene stack already marked the scene itself visible. Remove
/// the marker once the entity's content is final, whether it loaded
/// successfully or failed, so a broken load can never hide a scene forever.
#[derive(Clone, Copy, Debug, Default, Component, Reflect)]
#[reflect(Component, Default)]
pub struct SceneContentLoading;

/// Convenience methods for queuing scene commands through Bevy [`Commands`].
pub trait SceneCommandsExt {
    /// Queues a command to open a scene with default options.
    fn open_scene(&mut self, source: SceneSource) -> &mut Self;

    /// Queues a command to open a scene with explicit options.
    fn open_scene_with_options(
        &mut self,
        source: SceneSource,
        options: OpenSceneOptions,
    ) -> &mut Self;

    /// Queues a command to close the current scene.
    fn close_current_scene(&mut self) -> &mut Self;

    /// Queues a command to close a target scene by id or key.
    fn close_scene(&mut self, target: impl Into<SceneTarget>) -> &mut Self;

    /// Queues a command to clear all scenes.
    fn clear_scenes(&mut self) -> &mut Self;

    /// Queues a command to clear all scenes and then open a new scene.
    fn clear_and_open_scene(&mut self, source: SceneSource) -> &mut Self;
}

impl<'w, 's> SceneCommandsExt for Commands<'w, 's> {
    fn open_scene(&mut self, source: SceneSource) -> &mut Self {
        self.queue_scene_command(SceneCommand::open(source))
    }

    fn open_scene_with_options(
        &mut self,
        source: SceneSource,
        options: OpenSceneOptions,
    ) -> &mut Self {
        self.queue_scene_command(SceneCommand::open_with_options(source, options))
    }

    fn close_current_scene(&mut self) -> &mut Self {
        self.queue_scene_command(SceneCommand::CloseCurrent)
    }

    fn close_scene(&mut self, target: impl Into<SceneTarget>) -> &mut Self {
        self.queue_scene_command(SceneCommand::Close(target.into()))
    }

    fn clear_scenes(&mut self) -> &mut Self {
        self.queue_scene_command(SceneCommand::Clear)
    }

    fn clear_and_open_scene(&mut self, source: SceneSource) -> &mut Self {
        self.queue_scene_command(SceneCommand::clear_and_open(source))
    }
}

trait QueueSceneCommand {
    fn queue_scene_command(&mut self, command: SceneCommand) -> &mut Self;
}

impl<'w, 's> QueueSceneCommand for Commands<'w, 's> {
    fn queue_scene_command(&mut self, command: SceneCommand) -> &mut Self {
        // Queue commands through the world to keep call sites decoupled from message writers.
        self.queue(move |world: &mut World| {
            world.write_message(command);
        });
        self
    }
}

fn process_scene_commands(
    mut commands: MessageReader<SceneCommand>,
    mut stack: ResMut<SceneStack>,
    mut added: MessageWriter<SceneAdded>,
    mut removed: MessageWriter<SceneRemoved>,
    mut focused: MessageWriter<SceneFocused>,
    mut unfocused: MessageWriter<SceneUnfocused>,
    mut load_requested: MessageWriter<SceneLoadRequested>,
) {
    // Drain commands before applying them so stack mutations cannot affect this read pass.
    let scene_commands = commands.read().cloned().collect::<Vec<_>>();
    if scene_commands.is_empty() {
        return;
    }

    for command in scene_commands {
        apply_scene_command(
            command,
            &mut stack,
            &mut added,
            &mut removed,
            &mut load_requested,
        );
    }

    // Recompute focus and derived flags once per batch so callers observe only
    // the net focus transition, never transient intermediate stack states.
    update_runtime_flags(&mut stack, &mut focused, &mut unfocused);
}

fn apply_scene_command(
    command: SceneCommand,
    stack: &mut SceneStack,
    added: &mut MessageWriter<SceneAdded>,
    removed: &mut MessageWriter<SceneRemoved>,
    load_requested: &mut MessageWriter<SceneLoadRequested>,
) {
    match command {
        SceneCommand::Open { source, options } => {
            // Replacement options are applied before loading the new scene entry.
            if options.clear_stack {
                clear_stack(stack, removed);
            } else if options.close_current {
                close_current(stack, removed);
            }
            open_scene(source, options, stack, added, load_requested);
        }
        SceneCommand::CloseCurrent => close_current(stack, removed),
        SceneCommand::Close(target) => close_target(target, stack, removed),
        SceneCommand::Clear => clear_stack(stack, removed),
        SceneCommand::ClearAndOpen { source, options } => {
            clear_stack(stack, removed);
            open_scene(source, options, stack, added, load_requested);
        }
    }
}

fn open_scene(
    source: SceneSource,
    options: OpenSceneOptions,
    stack: &mut SceneStack,
    added: &mut MessageWriter<SceneAdded>,
    load_requested: &mut MessageWriter<SceneLoadRequested>,
) {
    let id = stack.allocate_id();
    // Push before requesting load so bridge systems can attach content to the new owner.
    stack.entries.push(SceneStackEntry {
        id,
        key: options.key,
        source: source.clone(),
        presentation: options.presentation,
        flags: SceneRuntimeFlags::default(),
    });
    added.write(SceneAdded { scene_id: id });
    load_requested.write(SceneLoadRequested {
        scene_id: id,
        source,
    });
}

fn close_current(stack: &mut SceneStack, removed: &mut MessageWriter<SceneRemoved>) {
    // Closing an empty stack is a no-op so callers can safely request cleanup.
    if let Some(entry) = stack.entries.pop() {
        removed.write(SceneRemoved { scene_id: entry.id });
    }
}

fn close_target(
    target: SceneTarget,
    stack: &mut SceneStack,
    removed: &mut MessageWriter<SceneRemoved>,
) {
    let target_scene_position = match target {
        SceneTarget::Id(scene_id) => stack.entries.iter().position(|entry| entry.id == scene_id),
        SceneTarget::Key(scene_key) => stack
            .entries
            .iter()
            .position(|entry| entry.key.as_ref() == Some(&scene_key)),
    };

    if let Some(target_scene_position) = target_scene_position {
        let entry = stack.entries.remove(target_scene_position);
        removed.write(SceneRemoved { scene_id: entry.id });
    }
}

fn clear_stack(stack: &mut SceneStack, removed: &mut MessageWriter<SceneRemoved>) {
    // Pop from the top so removal messages follow visible stack order.
    while let Some(entry) = stack.entries.pop() {
        removed.write(SceneRemoved { scene_id: entry.id });
    }
}

fn cleanup_removed_scene_entities(
    mut commands: Commands,
    mut removed: MessageReader<SceneRemoved>,
    owned_entities: Query<(Entity, &SceneOwner, Option<&ChildOf>)>,
    owners: Query<&SceneOwner>,
) {
    let removed_scene_ids = removed
        .read()
        .map(|message| message.scene_id)
        .collect::<Vec<_>>();

    if removed_scene_ids.is_empty() {
        return;
    }

    for (owned_entity, scene_owner, parent_link) in &owned_entities {
        if !removed_scene_ids.contains(&scene_owner.scene_id) {
            continue;
        }

        // Despawn only top-level owned entities; child cleanup follows the hierarchy.
        let parent_is_removed_scene_owned = parent_link
            .and_then(|parent_link| owners.get(parent_link.0).ok())
            .is_some_and(|parent_owner| removed_scene_ids.contains(&parent_owner.scene_id));

        if !parent_is_removed_scene_owned {
            commands.entity(owned_entity).despawn();
        }
    }
}

fn sync_scene_entity_visibility(
    stack: Res<SceneStack>,
    mut owned_visibilities: Query<(&SceneOwner, Option<&ChildOf>, &mut Visibility)>,
    owners: Query<&SceneOwner>,
    loading_owners: Query<&SceneOwner, With<SceneContentLoading>>,
) {
    // A scene stays hidden while any entity it owns is still loading,
    // regardless of stack presentation, so content never renders mid-build.
    let loading_scene_ids: std::collections::HashSet<SceneId> =
        loading_owners.iter().map(|owner| owner.scene_id).collect();

    for (scene_owner, parent_link, mut visibility) in &mut owned_visibilities {
        // Drive only scene-root entities; owned children follow through Bevy's
        // visibility inheritance, which keeps authored child visibility intact.
        let parent_owned_by_same_scene = parent_link
            .and_then(|parent_link| owners.get(parent_link.0).ok())
            .is_some_and(|parent_owner| parent_owner.scene_id == scene_owner.scene_id);
        if parent_owned_by_same_scene {
            continue;
        }

        let scene_is_ready = !loading_scene_ids.contains(&scene_owner.scene_id);
        let scene_visibility = if stack.is_visible(scene_owner.scene_id) && scene_is_ready {
            Visibility::Inherited
        } else {
            Visibility::Hidden
        };
        // Compare before writing so unchanged scenes do not trigger change detection.
        if *visibility != scene_visibility {
            *visibility = scene_visibility;
        }
    }
}

fn update_runtime_flags(
    stack: &mut SceneStack,
    focused: &mut MessageWriter<SceneFocused>,
    unfocused: &mut MessageWriter<SceneUnfocused>,
) {
    let previous_focus = stack
        .entries
        .iter()
        .find(|entry| entry.flags.focused)
        .map(|entry| entry.id);

    let mut covered = false;
    let mut input_blocked = false;
    let mut update_blocked = false;

    for entry in stack.entries.iter_mut().rev() {
        // Walk from top to bottom so upper presentations control lower scene flags.
        entry.flags.visible = !covered;
        entry.flags.interactive = !input_blocked;
        entry.flags.updating = !update_blocked;
        entry.flags.focused = false;

        covered |= entry.presentation.covers_previous;
        input_blocked |= entry.presentation.blocks_previous_input;
        update_blocked |= entry.presentation.blocks_previous_update;
    }

    let new_focus = stack
        .entries
        .iter_mut()
        .rev()
        .find(|entry| entry.flags.interactive)
        .map(|entry| {
            entry.flags.focused = true;
            entry.id
        });

    if previous_focus != new_focus {
        // Focus lifecycle messages let callers respond without inspecting stack internals.
        if let Some(previous_focus) = previous_focus {
            if stack.entries.iter().any(|entry| entry.id == previous_focus) {
                unfocused.write(SceneUnfocused {
                    scene_id: previous_focus,
                });
            }
        }

        if let Some(new_focus) = new_focus {
            focused.write(SceneFocused {
                scene_id: new_focus,
            });
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn scene_presentation_defaults_to_fullscreen() {
        assert_eq!(ScenePresentation::default(), ScenePresentation::FULLSCREEN);
        assert!(ScenePresentation::default().covers_previous);
        assert!(ScenePresentation::default().blocks_previous_input);
        assert!(ScenePresentation::default().blocks_previous_update);
    }

    #[test]
    fn open_options_builder_sets_requested_values() {
        let options = OpenSceneOptions::default()
            .with_key("pause")
            .with_presentation(ScenePresentation::PAUSE_OVERLAY)
            .close_current();

        assert_eq!(options.key, Some(SceneKey::new("pause")));
        assert_eq!(options.presentation, ScenePresentation::PAUSE_OVERLAY);
        assert!(options.close_current);
        assert!(!options.clear_stack);
    }

    #[test]
    fn scene_sources_support_bsn_scenes_and_runtime_keys() {
        assert_eq!(
            SceneSource::bsn_scene("assets/scene"),
            SceneSource::BsnScene {
                key: "assets/scene".to_string()
            }
        );
        assert_eq!(
            SceneSource::runtime("pause_menu"),
            SceneSource::Runtime {
                key: SceneKey::new("pause_menu")
            }
        );
    }

    #[test]
    fn command_helpers_construct_expected_commands() {
        let source = SceneSource::bsn_scene("levels/one");
        assert_eq!(
            SceneCommand::open(source.clone()),
            SceneCommand::Open {
                source: source.clone(),
                options: OpenSceneOptions::default()
            }
        );
        assert_eq!(
            SceneCommand::clear_and_open(source.clone()),
            SceneCommand::ClearAndOpen {
                source,
                options: OpenSceneOptions::default()
            }
        );
    }

    #[test]
    fn scene_stack_starts_empty_with_first_id_available() {
        let stack = SceneStack::default();
        assert!(stack.is_empty());
        assert_eq!(stack.len(), 0);
        assert_eq!(stack.current(), None);
        assert_eq!(stack.next_scene_id(), SceneId(1));
    }

    #[test]
    fn processing_open_command_pushes_scene_and_focuses_it() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::bsn_scene("levels/one")));

        app.update();

        let stack = app.world().resource::<SceneStack>();
        assert_eq!(stack.len(), 1);
        let entry = stack.current().expect("opened scene should be stacked");
        assert_eq!(entry.id, SceneId(1));
        assert_eq!(entry.source, SceneSource::bsn_scene("levels/one"));
        assert!(entry.flags.visible);
        assert!(entry.flags.interactive);
        assert!(entry.flags.updating);
        assert!(entry.flags.focused);
    }

    #[test]
    fn presentation_flags_control_lower_scene_runtime_flags() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.world_mut()
            .write_message(SceneCommand::open_with_options(
                SceneSource::runtime("pause"),
                OpenSceneOptions::default()
                    .with_presentation(ScenePresentation::PAUSE_OVERLAY)
                    .with_key("pause"),
            ));

        app.update();

        let stack = app.world().resource::<SceneStack>();
        let gameplay = &stack.entries()[0];
        let pause = &stack.entries()[1];

        assert!(gameplay.flags.visible);
        assert!(!gameplay.flags.interactive);
        assert!(!gameplay.flags.updating);
        assert!(!gameplay.flags.focused);
        assert!(pause.flags.visible);
        assert!(pause.flags.interactive);
        assert!(pause.flags.updating);
        assert!(pause.flags.focused);
    }

    #[test]
    fn close_current_restores_previous_scene_focus() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("menu")));
        app.update();

        app.world_mut().write_message(SceneCommand::CloseCurrent);
        app.update();

        let stack = app.world().resource::<SceneStack>();
        assert_eq!(stack.len(), 1);
        assert_eq!(stack.current().map(|entry| entry.id), Some(SceneId(1)));
        assert_eq!(stack.focused().map(|entry| entry.id), Some(SceneId(1)));
    }

    #[test]
    fn closing_input_overlay_restores_underlying_scene_input() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("main-menu")));
        app.world_mut()
            .write_message(SceneCommand::open_with_options(
                SceneSource::runtime("options"),
                OpenSceneOptions::default()
                    .with_key("options")
                    .with_presentation(ScenePresentation::INPUT_BLOCKING_OVERLAY),
            ));
        app.update();

        app.world_mut().write_message(SceneCommand::CloseCurrent);
        app.update();

        let stack = app.world().resource::<SceneStack>();
        let main_menu = stack
            .current()
            .expect("main menu should remain after closing options");
        assert_eq!(stack.len(), 1);
        assert_eq!(main_menu.source, SceneSource::runtime("main-menu"));
        assert!(main_menu.flags.visible);
        assert!(main_menu.flags.interactive);
        assert!(main_menu.flags.updating);
        assert!(main_menu.flags.focused);
    }

    #[test]
    fn clear_and_open_replaces_stack() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.world_mut()
            .write_message(SceneCommand::clear_and_open(SceneSource::bsn_scene(
                "levels/two",
            )));

        app.update();

        let stack = app.world().resource::<SceneStack>();
        assert_eq!(stack.len(), 1);
        let entry = stack
            .current()
            .expect("replacement scene should be stacked");
        assert_eq!(entry.id, SceneId(2));
        assert_eq!(entry.source, SceneSource::bsn_scene("levels/two"));
    }

    #[test]
    fn lifecycle_messages_are_emitted_for_focus_changes() {
        let mut app = test_app();
        app.init_resource::<LifecycleLog>();
        app.add_systems(Last, collect_lifecycle_messages);

        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("menu")));
        app.update();

        let log = app.world().resource::<LifecycleLog>();
        // One frame's command batch emits only the net focus transition, not
        // transient focus flips for intermediate stack states.
        assert_eq!(log.0, vec!["added:1", "added:2", "focused:2"]);
    }

    #[test]
    fn close_by_key_removes_target_scene() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.world_mut()
            .write_message(SceneCommand::open_with_options(
                SceneSource::runtime("pause"),
                OpenSceneOptions::default().with_key("pause"),
            ));
        app.update();

        app.world_mut()
            .write_message(SceneCommand::Close(SceneTarget::Key(SceneKey::new(
                "pause",
            ))));
        app.update();

        let stack = app.world().resource::<SceneStack>();
        assert_eq!(stack.len(), 1);
        assert_eq!(stack.current().map(|entry| entry.id), Some(SceneId(1)));
        assert_eq!(stack.get_by_key(&SceneKey::new("pause")), None);
    }

    #[test]
    fn removing_scene_despawns_only_owned_entities() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("menu")));
        app.update();

        let gameplay_entity = app
            .world_mut()
            .spawn(SceneOwner {
                scene_id: SceneId(1),
            })
            .id();
        let menu_entity = app
            .world_mut()
            .spawn(SceneOwner {
                scene_id: SceneId(2),
            })
            .id();
        let global_entity = app.world_mut().spawn_empty().id();

        app.world_mut()
            .write_message(SceneCommand::Close(SceneTarget::Id(SceneId(2))));
        app.update();

        assert!(app.world().get_entity(gameplay_entity).is_ok());
        assert!(app.world().get_entity(menu_entity).is_err());
        assert!(app.world().get_entity(global_entity).is_ok());
    }

    #[test]
    fn covered_scene_entities_are_hidden_until_uncovered() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.update();

        let owned_entity = app
            .world_mut()
            .spawn((
                SceneOwner {
                    scene_id: SceneId(1),
                },
                Visibility::default(),
            ))
            .id();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("main-menu")));
        app.update();

        assert_eq!(
            app.world().get::<Visibility>(owned_entity),
            Some(&Visibility::Hidden),
            "entities in covered scenes should be hidden"
        );

        app.world_mut().write_message(SceneCommand::CloseCurrent);
        app.update();

        assert_eq!(
            app.world().get::<Visibility>(owned_entity),
            Some(&Visibility::Inherited),
            "entities should become visible again once uncovered"
        );
    }

    #[test]
    fn loading_scene_entities_stay_hidden_even_when_stack_visible() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.update();

        let loading_entity = app
            .world_mut()
            .spawn((
                SceneOwner {
                    scene_id: SceneId(1),
                },
                SceneContentLoading,
                Visibility::default(),
            ))
            .id();
        app.update();

        assert_eq!(
            app.world().get::<Visibility>(loading_entity),
            Some(&Visibility::Hidden),
            "a scene-owned entity still loading must stay hidden even though the stack marks the scene visible"
        );
    }

    #[test]
    fn scene_becomes_visible_once_loading_marker_clears() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.update();

        let loading_entity = app
            .world_mut()
            .spawn((
                SceneOwner {
                    scene_id: SceneId(1),
                },
                SceneContentLoading,
                Visibility::default(),
            ))
            .id();
        app.update();
        assert_eq!(
            app.world().get::<Visibility>(loading_entity),
            Some(&Visibility::Hidden)
        );

        app.world_mut()
            .entity_mut(loading_entity)
            .remove::<SceneContentLoading>();
        app.update();

        assert_eq!(
            app.world().get::<Visibility>(loading_entity),
            Some(&Visibility::Inherited),
            "the scene should reveal once nothing it owns is still loading"
        );
    }

    #[test]
    fn loading_marker_on_child_entity_keeps_whole_scene_hidden() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.update();

        let scene_owner = SceneOwner {
            scene_id: SceneId(1),
        };
        let root_entity = app
            .world_mut()
            .spawn((scene_owner, Visibility::default()))
            .id();
        app.world_mut()
            .spawn((scene_owner, SceneContentLoading, ChildOf(root_entity)));
        app.update();

        assert_eq!(
            app.world().get::<Visibility>(root_entity),
            Some(&Visibility::Hidden),
            "a loading descendant anywhere in the owned subtree must hide the whole scene root"
        );
    }

    #[test]
    fn covered_ready_scene_stays_hidden_from_presentation_not_readiness() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.update();

        let ready_entity = app
            .world_mut()
            .spawn((
                SceneOwner {
                    scene_id: SceneId(1),
                },
                Visibility::default(),
            ))
            .id();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("main-menu")));
        app.update();

        assert_eq!(
            app.world().get::<Visibility>(ready_entity),
            Some(&Visibility::Hidden),
            "a ready scene covered by another scene must still be hidden by presentation"
        );
    }

    #[test]
    fn scene_stack_reports_update_and_visibility_state_by_id() {
        let mut app = test_app();
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("gameplay")));
        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::runtime("main-menu")));
        app.update();

        let stack = app.world().resource::<SceneStack>();
        assert!(!stack.is_updating(SceneId(1)));
        assert!(!stack.is_visible(SceneId(1)));
        assert!(stack.is_updating(SceneId(2)));
        assert!(stack.is_visible(SceneId(2)));
        // Unknown scenes are treated as inert so stale owners never keep running.
        assert!(!stack.is_updating(SceneId(99)));
        assert!(!stack.is_visible(SceneId(99)));
    }

    #[test]
    fn open_scene_emits_load_request_for_bsn_bridge() {
        let mut app = test_app();
        app.init_resource::<LoadRequestLog>();
        app.add_systems(Last, collect_load_requests);

        app.world_mut()
            .write_message(SceneCommand::open(SceneSource::bsn_scene("levels/one")));
        app.update();

        let log = app.world().resource::<LoadRequestLog>();
        assert_eq!(
            log.0,
            vec![(SceneId(1), SceneSource::bsn_scene("levels/one"))]
        );
    }

    fn test_app() -> App {
        let mut app = App::new();
        app.add_plugins(MinimalPlugins);
        app.add_plugins(FoundationSceneStackPlugin);
        app
    }

    #[derive(Default, Resource)]
    struct LifecycleLog(Vec<String>);

    #[derive(Default, Resource)]
    struct LoadRequestLog(Vec<(SceneId, SceneSource)>);

    fn collect_lifecycle_messages(
        mut added: MessageReader<SceneAdded>,
        mut removed: MessageReader<SceneRemoved>,
        mut focused: MessageReader<SceneFocused>,
        mut unfocused: MessageReader<SceneUnfocused>,
        mut log: ResMut<LifecycleLog>,
    ) {
        for message in added.read() {
            log.0.push(format!("added:{}", message.scene_id.0));
        }
        for message in removed.read() {
            log.0.push(format!("removed:{}", message.scene_id.0));
        }
        for message in unfocused.read() {
            log.0.push(format!("unfocused:{}", message.scene_id.0));
        }
        for message in focused.read() {
            log.0.push(format!("focused:{}", message.scene_id.0));
        }
    }

    fn collect_load_requests(
        mut load_requests: MessageReader<SceneLoadRequested>,
        mut log: ResMut<LoadRequestLog>,
    ) {
        for message in load_requests.read() {
            log.0.push((message.scene_id, message.source.clone()));
        }
    }
}
